### ISSUE TITLE
Popup won't open on click after tab changes

### ISSUE THREAD

**Issue by fapdash** [EMPRI-DEVOPS/empri-browser-extension#16]
## Browser

- Firefox
- Chrome

## Reproduction

1. Visit https://github.com/EMPRI-DEVOPS/empri-browser-extension/pull/15/commits
2. Change tab to `Conversation`
3. Change tab back to `Commits` (make sure no full page reload is happening, this sometimes happens for whatever reason)
4. Try to open the redaction popup

## Expected

Popup opens.

## Actual

Popup doesn't open. No reaction to the click.

**Comment by fapdash** [comment]
In those instances `tsClickHandler(event)` doesn't get called after clicking on a date. Not sure why though..

**Comment by cburkert** [comment]
The error was caused because in same DOM refresh cases, the `redacted` state is kept but the listeners are gone.
As 3a199e831137ae6a000b2c9e51e37b4d1a128325 then prevents a reinit of the popup, no new listeners were set.
With 96cbe03339cd071fffc932f0c1f72d37f5768977 we can safely remove the checks from 3a199e831137ae6a000b2c9e51e37b4d1a128325 and still fix #12
